export enum AuthMutationTypes {
  SET_USER = "SET_USER",
  SET_AUTH = "SET_AUTH",
  PURGE_AUTH = "PURGE_AUTH",
  SET_GLOBAL_LOADING = "SET_GLOBAL_LOADING",
  SET_SUBNAME = "SET_SUBNAME",
  SET_CLAIMS = "SET_CLAIMS",
  SET_MOUNT = "SET_MOUNT",
}
